### ISSUE TITLE
Value Member

### ISSUE THREAD

**Issue by rcbeyra** [AndersMalmgren/Knockout.Combobox#5]
Is there a way to get instead of the label value the selected value, Ex. I'm filling the combo with a model (Name & ID), I'm displaying the label but I want the ID, I was checking the source and there is only value member available. A version with both values would be really helpful, other than that. Congratulation really cool job.

**Comment by AndersMalmgren** [comment]
You get the entire selected object/viewmodel,  you can get the Id from that object?

**Comment by AndersMalmgren** [comment]
Quick demo

http://jsfiddle.net/AWHhr/71/

**Comment by rcbeyra** [comment]
Awesome!! good job....

**Comment by AndersMalmgren** [comment]
I hope that solves your problem, im closing the issue
