### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by EdgarVerona** [AndersMalmgren/Knockout.Combobox#6]
Greetings!  Excellent work you've done here!

This combo box is perfect for an internal project I am working on, but my company would not allow me to use it on even an internal project unless it has a known license that it can vet (MIT or what-have-you).

Would you be willing to MIT license this code, and add an MIT license file to the project?

**Comment by AndersMalmgren** [comment]
The nuget package has license info, but haven't added it as a file to the source, can fix.

**Comment by EdgarVerona** [comment]
That would be fantastic, thank you!

**Comment by AndersMalmgren** [comment]
License added
